name: Outputs test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: alpine
    outputs:
      output1: ${{ true }}
    steps:
      - name: Test
        run: echo "Sets"
  display:
    runs-on: ubuntu-latest
    needs: build
    if: needs.output1
    steps:
      - name: Test
        run: echo "Runs"
